// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihHHLwWmy1h6qcbu7UOaXKaSsi8ECPMg',
    appId: '1:58715525124:web:61378f87e2440465a8e551',
    messagingSenderId: '58715525124',
    projectId: 'masterbysasha',
    authDomain: 'masterbysasha.firebaseapp.com',
    storageBucket: 'masterbysasha.appspot.com',
    measurementId: 'G-TJVVD0CMQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqNiiaFetMQ0ZSpzOisdqinRGqahc63c',
    appId: '1:58715525124:android:4b2af8eeed3db175a8e551',
    messagingSenderId: '58715525124',
    projectId: 'masterbysasha',
    storageBucket: 'masterbysasha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CoxfKIxSKzS-fGRtWSBlp0FJMlVggiY',
    appId: '1:58715525124:ios:081a863e5198e36da8e551',
    messagingSenderId: '58715525124',
    projectId: 'masterbysasha',
    storageBucket: 'masterbysasha.appspot.com',
    iosClientId: '58715525124-c7jrl5tm2bk92dd4hq7fbsn09pb5vr38.apps.googleusercontent.com',
    iosBundleId: 'com.example.sashamaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CoxfKIxSKzS-fGRtWSBlp0FJMlVggiY',
    appId: '1:58715525124:ios:081a863e5198e36da8e551',
    messagingSenderId: '58715525124',
    projectId: 'masterbysasha',
    storageBucket: 'masterbysasha.appspot.com',
    iosClientId: '58715525124-c7jrl5tm2bk92dd4hq7fbsn09pb5vr38.apps.googleusercontent.com',
    iosBundleId: 'com.example.sashamaster',
  );
}
